export let ActionTypes = {
	NEW_USER: 'NEW_USER',
	NEW_LOGIN: 'NEW_LOGIN',
	CURRENT_USER: 'CURRENT_USER',
	SAVE_EDIT: 'SAVE_EDIT',
	UPDATED_USER: 'UPDATED_USER',
	ALL_COMPANIES: 'ALL_COMPANIES',
	ALL_USERS: 'ALL_USERS',
	ONE_USER: 'ONE_USER',
	LOGOUT_USER: 'LOGOUT_USER',
};
